services:
    db_coin:
        container_name: pg_coin
        image: postgres:17-alpine3.21
        environment:
            - POSTGRES_USER=m2i
            - POSTGRES_PASSWORD=test1234
            - POSTGRES_DB=db_coin
        volumes:
            -  './.db_coin:/var/lib/postgresql/data'
        ports:
            - '5432:5432'

    php_coin:
        container_name: php_coin
        build: ./.docker/php
        working_dir: /www/symfony
        volumes:
            - './symfony:/www/symfony'

    server_coin:
        container_name: server_coin
        image: nginx:1.27-alpine3.20
        working_dir: /www
        volumes:
            - './symfony:/www/symfony'
            - './.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8080:80'
